//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34014.
// 
#pragma warning disable 1591

namespace CentrosDeportivos.SportCenterService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SportCenterServiceSOAP", Namespace="http://www.example.org/SportCenterService/")]
    public partial class SportCenterService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getSportCenterOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSportCentersOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSportsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getFieldsOkOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SportCenterService() {
            this.Url = global::CentrosDeportivos.Properties.Settings.Default.CentrosDeportivos_SportCenterService_SportCenterService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getSportCenterCompletedEventHandler getSportCenterCompleted;
        
        /// <remarks/>
        public event getSportCentersCompletedEventHandler getSportCentersCompleted;
        
        /// <remarks/>
        public event getSportsCompletedEventHandler getSportsCompleted;
        
        /// <remarks/>
        public event getFieldsCompletedEventHandler getFieldsCompleted;
        
        /// <remarks/>
        public event getFieldsOkCompletedEventHandler getFieldsOkCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/SportCenterService/getSportCenter", RequestNamespace="http://www.example.org/SportCenterService/", ResponseNamespace="http://www.example.org/SportCenterService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("sportCenter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SportCenter getSportCenter([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_sc) {
            object[] results = this.Invoke("getSportCenter", new object[] {
                        id_sc});
            return ((SportCenter)(results[0]));
        }
        
        /// <remarks/>
        public void getSportCenterAsync(int id_sc) {
            this.getSportCenterAsync(id_sc, null);
        }
        
        /// <remarks/>
        public void getSportCenterAsync(int id_sc, object userState) {
            if ((this.getSportCenterOperationCompleted == null)) {
                this.getSportCenterOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSportCenterOperationCompleted);
            }
            this.InvokeAsync("getSportCenter", new object[] {
                        id_sc}, this.getSportCenterOperationCompleted, userState);
        }
        
        private void OngetSportCenterOperationCompleted(object arg) {
            if ((this.getSportCenterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSportCenterCompleted(this, new getSportCenterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/SportCenterService/getSportCenters", RequestNamespace="http://www.example.org/SportCenterService/", ResponseNamespace="http://www.example.org/SportCenterService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("centers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SportCenter[] getSportCenters() {
            object[] results = this.Invoke("getSportCenters", new object[0]);
            return ((SportCenter[])(results[0]));
        }
        
        /// <remarks/>
        public void getSportCentersAsync() {
            this.getSportCentersAsync(null);
        }
        
        /// <remarks/>
        public void getSportCentersAsync(object userState) {
            if ((this.getSportCentersOperationCompleted == null)) {
                this.getSportCentersOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSportCentersOperationCompleted);
            }
            this.InvokeAsync("getSportCenters", new object[0], this.getSportCentersOperationCompleted, userState);
        }
        
        private void OngetSportCentersOperationCompleted(object arg) {
            if ((this.getSportCentersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSportCentersCompleted(this, new getSportCentersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/SportCenterService/getSports", RequestNamespace="http://www.example.org/SportCenterService/", ResponseNamespace="http://www.example.org/SportCenterService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("sports", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sport[] getSports([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_sc) {
            object[] results = this.Invoke("getSports", new object[] {
                        id_sc});
            return ((Sport[])(results[0]));
        }
        
        /// <remarks/>
        public void getSportsAsync(int id_sc) {
            this.getSportsAsync(id_sc, null);
        }
        
        /// <remarks/>
        public void getSportsAsync(int id_sc, object userState) {
            if ((this.getSportsOperationCompleted == null)) {
                this.getSportsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSportsOperationCompleted);
            }
            this.InvokeAsync("getSports", new object[] {
                        id_sc}, this.getSportsOperationCompleted, userState);
        }
        
        private void OngetSportsOperationCompleted(object arg) {
            if ((this.getSportsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSportsCompleted(this, new getSportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/SportCenterService/getFields", RequestNamespace="http://www.example.org/SportCenterService/", ResponseNamespace="http://www.example.org/SportCenterService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("fields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Field[] getFields([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_sport, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_sc) {
            object[] results = this.Invoke("getFields", new object[] {
                        id_sport,
                        id_sc});
            return ((Field[])(results[0]));
        }
        
        /// <remarks/>
        public void getFieldsAsync(int id_sport, int id_sc) {
            this.getFieldsAsync(id_sport, id_sc, null);
        }
        
        /// <remarks/>
        public void getFieldsAsync(int id_sport, int id_sc, object userState) {
            if ((this.getFieldsOperationCompleted == null)) {
                this.getFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFieldsOperationCompleted);
            }
            this.InvokeAsync("getFields", new object[] {
                        id_sport,
                        id_sc}, this.getFieldsOperationCompleted, userState);
        }
        
        private void OngetFieldsOperationCompleted(object arg) {
            if ((this.getFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFieldsCompleted(this, new getFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.example.org/SportCenterService/getFieldsOk", RequestNamespace="http://www.example.org/SportCenterService/", ResponseNamespace="http://www.example.org/SportCenterService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("fields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Field[] getFieldsOk([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_sport, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int id_sc, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string date) {
            object[] results = this.Invoke("getFieldsOk", new object[] {
                        id_sport,
                        id_sc,
                        date});
            return ((Field[])(results[0]));
        }
        
        /// <remarks/>
        public void getFieldsOkAsync(int id_sport, int id_sc, string date) {
            this.getFieldsOkAsync(id_sport, id_sc, date, null);
        }
        
        /// <remarks/>
        public void getFieldsOkAsync(int id_sport, int id_sc, string date, object userState) {
            if ((this.getFieldsOkOperationCompleted == null)) {
                this.getFieldsOkOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetFieldsOkOperationCompleted);
            }
            this.InvokeAsync("getFieldsOk", new object[] {
                        id_sport,
                        id_sc,
                        date}, this.getFieldsOkOperationCompleted, userState);
        }
        
        private void OngetFieldsOkOperationCompleted(object arg) {
            if ((this.getFieldsOkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getFieldsOkCompleted(this, new getFieldsOkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SportCenterService/")]
    public partial class SportCenter {
        
        private int idField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string imgField;
        
        private Field[] fieldsField;
        
        private Sport[] sportsField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("fields", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Field[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("sports", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sport[] sports {
            get {
                return this.sportsField;
            }
            set {
                this.sportsField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SportCenterService/")]
    public partial class Field {
        
        private int idField;
        
        private int id_scField;
        
        private int id_sportField;
        
        private string nameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_sc {
            get {
                return this.id_scField;
            }
            set {
                this.id_scField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_sport {
            get {
                return this.id_sportField;
            }
            set {
                this.id_sportField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/SportCenterService/")]
    public partial class Sport {
        
        private int idField;
        
        private int id_scField;
        
        private string nameField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id_sc {
            get {
                return this.id_scField;
            }
            set {
                this.id_scField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getSportCenterCompletedEventHandler(object sender, getSportCenterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSportCenterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSportCenterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SportCenter Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SportCenter)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getSportCentersCompletedEventHandler(object sender, getSportCentersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSportCentersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSportCentersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SportCenter[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SportCenter[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getSportsCompletedEventHandler(object sender, getSportsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Sport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Sport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getFieldsCompletedEventHandler(object sender, getFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Field[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Field[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getFieldsOkCompletedEventHandler(object sender, getFieldsOkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getFieldsOkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getFieldsOkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Field[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Field[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591